services:
  node-red:
    image: nodered/node-red:3.1.11
    container_name: node-red-custom-node-test
    platform: linux/amd64
    volumes:
      - ./:/node-red-custom-node
      - ./node-red:/data
    ports:
      - "1880:1880"
    networks:
      - node-ready-custom-node-test-network

networks:
  node-ready-custom-node-test-network:
